name: .NET MAUI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET MAUI Workloads
      run: dotnet workload install maui-android

    - name: Install dependencies
      run: dotnet restore ./MauiApp1/MauiApp1.sln

    - name: Build the project
      run: dotnet build --configuration Release ./MauiApp1/MauiApp1.sln

    - name: Run tests
      run: dotnet test --configuration Release ./MauiApp1/MauiApp1.sln

  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET MAUI Workloads
      run: dotnet workload install maui-android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        ndk-version: 21.4.7075529

    - name: Install dependencies
      run: dotnet restore ./MauiApp1/MauiApp1.sln

    - name: Build the Android project
      run: dotnet build --configuration Release -f net8.0-android ./MauiApp1/MauiApp1.sln

    - name: Run Android tests
      run: dotnet test --configuration Release -f net8.0-android ./MauiApp1/MauiApp1.sln

  ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET MAUI Workloads
      run: dotnet workload install maui-ios

    - name: Install dependencies
      run: dotnet restore ./MauiApp1/MauiApp1.sln

    - name: Build the iOS project
      run: dotnet build --configuration Release -f net8.0-ios ./MauiApp1/MauiApp1.sln

    - name: Run iOS tests
      run: dotnet test --configuration Release -f net8.0-ios ./MauiApp1/MauiApp1.sln
